export const MAIL_SEND_REQUEST = "MAIL_SEND_REQUEST";
export const MAIL_SEND_SUCCESS = "MAIL_SEND_SUCCESS";
export const MAIL_SEND_FAIL = "MAIL_SEND_FAIL";
export const MAIL_SEND_RESET = "MAIL_SEND_RESET";

export const MAIL_LIST_REQUEST = "MAIL_LIST_REQUEST";
export const MAIL_LIST_SUCCESS = "MAIL_LIST_SUCCESS";
export const MAIL_LIST_FAIL = "MAIL_LIST_FAIL";
export const MAIL_LIST_RESET = "MAIL_LIST_RESET";

export const MAIL_DELETE_REQUEST = "MAIL_DELETE_REQUEST";
export const MAIL_DELETE_SUCCESS = "MAIL_DELETE_SUCCESS";
export const MAIL_DELETE_FAIL = "MAIL_DELETE_FAIL";
export const MAIL_DELETE_RESET = "MAIL_DELETE_RESET";